# Generated by Django 5.1.1 on 2025-10-07 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='documents',
            field=models.FileField(blank=True, upload_to='seller_docs/'),
        ),
        migrations.AddField(
            model_name='sellers',
            name='onboarding_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
